[package]
name = "cache_line_size"
version = "0.2.0"
authors = ["Tinco Andringa <mail@tinco.nl>"]
edition = "2018"
description = "A crate that exposes the size of a cache line on the current architecture."
license = "MIT"
repository = "https://github.com/tinco/cache_line_size"

[dependencies]
